name: Build and Publish Documentation of dev Branch
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          pip install '.[doc]'
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "docs.deploy@unicorn.unicorn"
      - name: Build and deploy documentation
        run: mike deploy --push dev
