name: Release

on:
  release:
    types: [published]

jobs:
  build_wheel_and_sdist:
    name: Build wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install build
      - name: Build wheel and sdist
        run: python3 -m build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/pyrrha*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/*.tar.gz

  upload_pypi:
    needs: build_wheel_and_sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.2
        with:
          password: ${{ secrets.PYPI_DEPLOY_TOKEN }}

      - name: Upload Python packages for release notes
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            dist/*
