name: Release

on:
  release:
    types: [published]

jobs:
  build_wheel_and_sdist:
    name: Build wheel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install build
      - name: Build wheel and sdist
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: artifact_${{ matrix.python-version }}
          path: |
            dist/numbat*.whl
            dist/*.tar.gz

  upload_pypi:
    needs: build_wheel_and_sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact_*
          merge-multiple: true
          path: dist
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_DEPLOY_TOKEN }}

      - name: Upload Python packages for release notes
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            dist/*